### PR TITLE
build(deps): upgrade material-ui deps

### PR DESCRIPTION
**Pull request by stefensuhat**

### CODE REVIEW

**Comment by jedwards1211** [comment]
I need to keep supporting v4 because in my work we won't have time to migrate our entire app to v5 anytime soon.  Trying to decide whether I make imports like `material-ui-popup-state/mui4/HoverPopover` and `material-ui-popup-state/mui5/HoverPopover` or what...

**Comment by stefensuhat** [comment]
looks good. maybe make it major release so, others haven't update to latest v5 can still use it?

**Comment by jedwards1211** [comment]
I guess I'll just release a new version.  I worry about needing to make breaking changes to fix issues I encounter with v4.  MUIv5 is the most horrific set of breaking changes I've ever witnessed.

**Comment by jedwards1211** [comment]
Since MUI v5 is beta i guess I'll just use beta versions in this package for it, in case they make any more breaking changes

**Comment by jedwards1211** [comment]
Thanks for this!

**Pull request closed without merging**
